const FETCH_CURRENT_WEATHER_BY_ZIP_CODE = 'FETCH_CURRENT_WEATHER_BY_ZIP_CODE'
const REQUEST_CURRENT_WEATHER_BY_ZIP_CODE = 'REQUEST_CURRENT_WEATHER_BY_ZIP_CODE'
const RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE = 'RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE'
const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE'

export default {
  FETCH_CURRENT_WEATHER_BY_ZIP_CODE,
  REQUEST_CURRENT_WEATHER_BY_ZIP_CODE,
  RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE,
  UPDATE_ZIP_CODE
}