const FETCH_CURRENT_WEATHER_BY_ZIP_CODE = 'FETCH_CURRENT_WEATHER_BY_ZIP_CODE'
const REQUEST_CURRENT_WEATHER_BY_ZIP_CODE = 'REQUEST_CURRENT_WEATHER_BY_ZIP_CODE'
const RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE = 'RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE'
const SHOW_CURRENT_WEATHER_BY_ZIP_CODE_ERROR = 'SHOW_CURRENT_WEATHER_BY_ZIP_CODE_ERROR'
const HIDE_CURRENT_WEATHER_BY_ZIP_CODE_ERROR = 'HIDE_CURRENT_WEATHER_BY_ZIP_CODE_ERROR'
const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE'

export default {
  FETCH_CURRENT_WEATHER_BY_ZIP_CODE,
  REQUEST_CURRENT_WEATHER_BY_ZIP_CODE,
  RECEIVE_CURRENT_WEATHER_BY_ZIP_CODE,
  SHOW_CURRENT_WEATHER_BY_ZIP_CODE_ERROR,
  HIDE_CURRENT_WEATHER_BY_ZIP_CODE_ERROR,
  UPDATE_ZIP_CODE
}